version: '3.8'

services:
  app:
    build: .
    container_name: flask_app
    environment:
      - DATABASE_URL=postgresql://neondb_owner:NmXR1L2shrIn@db/neondb
      - FLASK_ENV=development
    ports:
      - "5000:5000"  # Expose Flask on port 5000
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: neondb_owner
      POSTGRES_PASSWORD: NmXR1L2shrIn
      POSTGRES_DB: neondb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
